### ISSUE TITLE
What is config.sh?

### ISSUE THREAD

**Issue by sixty4bit** [awslabs/aws-quickstart#1]
There is a reference to config.sh here:
https://github.com/awslabs/aws-quickstart/blob/master/mongodb/scripts/init.sh#L11

What is this file? Where can I find it? Is it required?

**Comment by karthikkrishnanv** [comment]
sixty4bit:

Yes, it's required. It's auto-generated on EC2 instances when you run the Cloudformation template in https://github.com/awslabs/aws-quickstart/blob/master/mongodb/templates/MongoDB-VPC.template. It basically sets some deployment context (VPC, MongDB version, WaitHandler etc). If you look into user-data, you can see the env vars being populated.

Karthik

**Comment by sixty4bit** [comment]
Ah! Thanks for the insight.
