### ISSUE TITLE
MongoError: not master

### ISSUE THREAD

**Issue by pdcarroll** [awslabs/aws-quickstart#2]
I used the mongodb templates to deploy a cluster on an existing VPC. When I try to connect to the PrimaryReplicaNode0 I'm getting a 13435 error ("not master and slaveOk=false").

**Comment by pdcarroll** [comment]
I was able to connect when I deployed the stack using a ClusterShardCount greater than 0. The problem described above was related to deployments with no sharding. Not sure if this is a bug or not?

**Comment by karthikkrishnanv** [comment]
I don't think sharding or no-sharding should have any impact on the connectivity. When you initialized the replica set (via rs.initialize()), it was on the PrimaryReplicaNode0 right ?  I'll give it it a try.

**Comment by pdcarroll** [comment]
I didn't initialize the set manually with rs.initialize (didn't know that was required). That's probably the issue.

**Comment by jpujari** [comment]
Sorry for being a newbie, but still didn't get where we have run the rs.initialize() method. If one of you can elaborate it would be helpful. I am getting the same error

**Comment by karthikkrishnanv** [comment]
@jpujari : Please refer to https://docs.mongodb.org/manual/tutorial/deploy-replica-set/ on how to initialize the replica set. Use rs.initialize() on say PrimaryReplicaNode0 and use rs.add() on other replica nodes

**Comment by jpujari** [comment]
Thanks
