### ISSUE TITLE
Re: Slight error in MongoDB-VPC.template

### ISSUE THREAD

**Issue by layiegbeyemi** [awslabs/aws-quickstart#3]
Hi

I found an 'error' in MongoDB-VPC.template which seems to have been corrected in the repo, but not in the published version (https://s3.amazonaws.com/quickstart-reference/mongodb/latest/templates/MongoDB-VPC.template).  This has to do with the index values used for the intrinsic function (Fn::Select) to select the AvailabilityZone for Resources "Secondary0NodeSubnet" and "Secondary1NodeSubnet".  Values used are 1 and 2 respectively.  As indexing starts with 0, attempting to use the template in a region that has less than three Availability Zones results causes the template to fall over.

**Comment by karthikkrishnanv** [comment]
Good catch! Will fix this.
