### ISSUE TITLE
Unable to access Mongo cluster in vpc from Java

### ISSUE THREAD

**Issue by yuganghu** [awslabs/aws-quickstart#4]
I was able to create a mongodb cluster with mongndb-vpc.template with CloudFormation. I can access PrimaryReplicator node on 27017 from ssh, however unable to access from outside, because the only node exposed to public is the NAT node, which did not expose the port 27017 port. Can someone help?

**Comment by yuganghu** [comment]
I was using https://s3.amazonaws.com/quickstart-reference/mongodb/latest/templates/MongoDB-NoVPC.template. The link was from https://s3.amazonaws.com/quickstart-reference/mongodb/latest/doc/MongoDB_on_the_AWS_Cloud.pdf.

**Comment by karthikkrishnanv** [comment]
@yuganghu : That is correct. MongoDB nodes are in private subnet and can be reached out only via NAT. Do you want them to be in Public Subnet with a EIP attached ?

**Comment by yuganghu** [comment]
Thanks Karthik! I was just wondering whether we can expose 27017 to public via NAT. Or just changing Network ACLs?

Do I have to make every node in a public subnet? Or just Primaries?

**Comment by yuganghu** [comment]
Any ideas? I have web services running in EC2. I am wondering how I can access MongoDB from my EC2 instance (in web service code). Is there other ways than forcing web service nodes and mongo nodes to be in the same subnet?
