### ISSUE TITLE
Mongo template for version 3.0 doesn't work anymore because config format is changed

### ISSUE THREAD

**Issue by milashenko** [awslabs/aws-quickstart#6]
<subj>

**Comment by iviarki** [comment]
The mongod config file no longer uses bind_ip variable, but rather "bindIp". This results in the sed command to comment out 127.0.0.1 not to make any changes.

A workaround that worked for me was to modify the downloaded init.sh script after it was downloaded to the instance:
                "sed --in-place 's/bind_ip/bindIp/g' init.sh\n",
Put that in around line 1775 into the MongoDB-VPC template and you should be good to go.

**Comment by milashenko** [comment]
@iviarki this is not the only change unfortunately. The "logpath" at line 228 doesn't work also.

**Comment by karthikkrishnanv** [comment]
@iviarki : Thanks for pointing it out. Yeah, looks like bind_ip got changed since we put the template out.
