### ISSUE TITLE
userdata init.sh fails

### ISSUE THREAD

**Issue by bostikmxb** [awslabs/aws-quickstart#7]
Hi, just started playing with MongoDB aws-quickstart.

when using template i connect to one node of the ReplicaSet instances but there's no mongod running on them.
in /home/ec2-user/mongodb/install.log i've found this error:
 
/var/lib/cloud/instance/scripts/part-001: ./init.sh: /bin/bash^M: bad interpreter: No such file or directory
Wed Nov 11 09:06:43 UTC 2015 signalFinalStatus.sh
Wed Nov 11 09:06:44 UTC 2015 END signalFinalStatus.sh

Don't know if i'm missing something or if i'm wrong somewhere.

Any help would be apreciated.

Thank you
Roberto

**Comment by bostikmxb** [comment]
The problem is on the init.sh file supplied by aws.
Probably they used a windows text editor so the file has ^M at the end of each line.

**Comment by karthikkrishnanv** [comment]
@bostikmxb - Thanks for the catch. Fixed EOF now.
